### ISSUE TITLE
Problem in search by id camelCase

### ISSUE THREAD

**Issue by DanExGithub** [sergioburdisso/solidscraper#1]
Hello Sergio,
I can not search by id using solidDom, but i can search by class 
![image](https://user-images.githubusercontent.com/24454992/87859958-d3f2c900-c928-11ea-9112-30cba5bd73a5.png)

**Comment by sergioburdisso** [comment]
I've performed some test and it worked, you didn't give me an URL,  but using a local file, serching by "#ContentPlaceHolder1_lblHora"  printed:

```
<span class="BoxValue" id="ContentPlaceHolder1_lblHora">
 15:42
</span>
```

So, more precisely, what's your issue? it seems to work here, try to post a complete example so we can replicate your error. :smile_cat:
